# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/bd/design_2/ip/design_2_top_0_0/design_2_top_0_0.xci
# IP: The module: 'design_2_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_top_0_0/design_2_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/bd/design_2/ip/design_2_top_0_0/design_2_top_0_0.xci
# IP: The module: 'design_2_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_top_0_0/design_2_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
