# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0.xci
# IP: The module: 'design_2_rst_clk_wiz_0_148M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_clk_wiz_0_148M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_clk_wiz_0_148M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_clk_wiz_0_148M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Vivado_Projects/FFT_FPGA/FFT_FPGA.srcs/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0.xci
# IP: The module: 'design_2_rst_clk_wiz_0_148M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_clk_wiz_0_148M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_clk_wiz_0_148M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Vivado_Projects/FFT_FPGA/FFT_FPGA.gen/sources_1/bd/design_2/ip/design_2_rst_clk_wiz_0_148M_0/design_2_rst_clk_wiz_0_148M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rst_clk_wiz_0_148M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
